name: student_profile_app
description: A Flutter project with editable student profile image.

publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_database: ^11.3.8 
  flutter_local_notifications: ^16.1.0

  



flutter:
  uses-material-design: true

  assets:
    - assets/images/